services:
  accident-monitoring:
    container_name: accident_monitoring_release
    image: accidentmonitoring:release
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    restart: always
