services:
  accident-monitor:
    container_name: accident-monitor-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    ports:
      - "5000:80"
    volumes:
      - ./src/Web:/app
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: always
